version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'skep-db'
      MYSQL_USER: 'skep'
      MYSQL_PASSWORD: '-NmM`-U]Z}z?6&3]'
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: 'mysql'
  app:
    restart: always
    build:
      context: ./
    working_dir: /app
    volumes:
      - ./backend/target:/app
    environment:
      PORT: 80
      DATASOURCE_URL: 'jdbc:mysql://mysql:3306/skep-db?useSSL=false&allowPublicKeyRetrieval=true'
      DATASOURCE_USERNAME: 'skep'
      DATASOURCE_PASSWORD: '-NmM`-U]Z}z?6&3]'
      BASE_URL: 'http://localhost'
    ports:
      - "80:80"
    command: java -Djava.security.egd=file:/dev/./urandom -jar backend-0.0.1-SNAPSHOT.jar
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - mysql
